由于最近入手了emacs作为自己的主力编辑器（主要是久仰orgmode大名），故使用orgmode作为了自己的主力标记语言。此处记录下orgmode的语法以供以后参考。
* 基础内容
个人建议，使用orgmode一定要使用emacs，很多快捷键真的很爽。

** headline
headline,其实就相当于其他文档中N级标题。之所以此处仍然称之为headline，因为orgmode中还有一个文件标题（TITLE），为了区分，因此使用headline.

在orgmode中使用headline的方式很简单，在文档中顶格写几个星号`*`，加一个空格，后面加上headline的名字，几个星号就是几级标题。

orgmode对headline提供了丰富的快捷键：
| 快捷键      | 功能                                       | 备注                              |
| <C-RET>   | 在当前headline *及内容* 后插入一个同级headline | 无headline时自动创建一个一级headline |
| <M-RET>   | 在当前headline后插入一个同级headline          | 同上                              |
| <M-right> | 降低当前headline的等级                       |                                  |
| <M-left>  | 提高当前headline的等级                       |                                  |
| <M-up>    | 将当前headline *及内容* 作为整体上移           |                                  |
| <M-down>  | 将当前headline *及内容* 作为整体下移           |                                  |

在org mode中，我们可以方便的折叠和展开headline,对于一个headline,按<Tab>切换此headline的折叠状态，按<S-Tab>切换整个文档的折叠状态。

headline的折叠状态有以下三种：
+ 折叠除了自身所有的内容，仅保留headline本身
+ 显示本身，切换子headline为上一状态
+ 展开所有内容

** 列表
用+、-、*加空格来组织无序列表，列表与headline一样，可以嵌套，像这样
#+BEGIN_SRC org
  + 哈哈
    * 嘻嘻
    * 拉拉
  + 我很快乐
    - 咚咚  
#+END_SRC
注意不要让*作为一级列表，不然会被认为是headline。

有序列表与无序列表类似，使用1.或1)加空格开头。

在列表后加两个空行表示结束。

列表的快捷键与headline的快捷键类似.
** 标记
*** 粗体
*粗体* 左右各一个星号表示粗体，星号左右需要有至少一个空格或英文标点。
*** 下划线
_下划线_ 前后用一个_包裹，其他同粗体
*** 删除线
+删除+ 前后各一个+，其他同粗体
** 块
*** 引用块
在org mode中引用需要借助于“块”来实现，像这样：
#+BEGIN_SRC org
  ,#+BEGIN_QUOTE
  我被引用了！
  ,#+END_QUOTE
#+END_SRC
效果是这样的：
#+BEGIN_QUOTE
我被引用了！
#+END_QUOTE
*** 代码
**** 插入代码
我们用块来插入代码，比如这是一段python代码
#+BEGIN_EXAMPLE
#+BEGIN_SRC python
print("hello,world")
#+END_SRC
#+END_EXAMPLE
效果是这样的：
#+BEGIN_SRC python
  print("hello,world")
#+END_SRC
在编辑代码块时会启动语言对应的主模式，所以如果配置得当，是可以享受自动缩进和代码补全的效果的。

光标在代码块时，使用C-c C-c运行代码。
** 链接
使用[ [链接] [链接描述] ]或[ [链接] ]（请自行去掉空格）来声明链接。如果是图片，那么使用图片的url即可。
